### ISSUE TITLE
start from "Error Cannot Find module 'Webpack-merge' " why is that sir?

### ISSUE THREAD

**Issue by RavenHunt** [BelinChung/HiApp#22]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle HiApp@3.0.0~predev: HiApp@3.0.0
6 info lifecycle HiApp@3.0.0~dev: HiApp@3.0.0
7 verbose lifecycle HiApp@3.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle HiApp@3.0.0~dev: PATH: D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Devel\otherhiaap\hiapp\node_modules\.bin;C:\Users\Lenovo\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Lenovo\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\PuTTY;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;E:\xampp\php;D:\Program Files\nodejs;C:\Users\Lenovo\AppData\Roaming\Composer\vendor\bin;C:\Users\Lenovo\AppData\Local\Microsoft\WindowsApps;C:\Users\Lenovo\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle HiApp@3.0.0~dev: CWD: D:\Devel\otherhiaap\hiapp
10 silly lifecycle HiApp@3.0.0~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
11 silly lifecycle HiApp@3.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle HiApp@3.0.0~dev: Failed to exec dev script
13 verbose stack Error: HiApp@3.0.0 dev: `node build/dev-server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid HiApp@3.0.0
15 verbose cwd D:\Devel\otherhiaap\hiapp
16 verbose Windows_NT 10.0.15063
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error HiApp@3.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the HiApp@3.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by RavenHunt** [comment]
Turns Out I just need to do some npm install in the root as well, now the App is running Thank You for Ur Example...

Now i got another issue.. :D
