### ISSUE TITLE
(node:1193) UnhandledPromiseRejectionWarning: Error: Source path does not exist: www/static/icons/ios/icon-small@2x.png

### ISSUE THREAD

**Issue by raulosandeep93** [BelinChung/HiApp#24]
Hi Team,

I'm following the steps mentioned in order to generate the application but getting below error while running the command: cordova platform add ios --save

Using cordova-fetch for cordova-ios@^4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.hiliaox.hiapp
	Name: HiApp
iOS project created with cordova-ios@4.5.4
(node:1193) UnhandledPromiseRejectionWarning: Error: Source path does not exist: www/static/icons/ios/icon-small@2x.png
    at updatePathInternal (/Users/sandeepraulo/Downloads/HiApp-master/hiapp/platforms/ios/cordova/node_modules/cordova-common/src/FileUpdater.js:145:19)
    at /Users/sandeepraulo/Downloads/HiApp-master/hiapp/platforms/ios/cordova/node_modules/cordova-common/src/FileUpdater.js:223:19
    at Array.forEach (<anonymous>)
    at Object.updatePaths (/Users/sandeepraulo/Downloads/HiApp-master/hiapp/platforms/ios/cordova/node_modules/cordova-common/src/FileUpdater.js:221:33)
    at updateIcons (/Users/sandeepraulo/Downloads/HiApp-master/hiapp/platforms/ios/cordova/lib/prepare.js:382:17)
    at /Users/sandeepraulo/Downloads/HiApp-master/hiapp/platforms/ios/cordova/lib/prepare.js:62:13
    at _fulfilled (/Users/sandeepraulo/Downloads/HiApp-master/hiapp/platforms/ios/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/sandeepraulo/Downloads/HiApp-master/hiapp/platforms/ios/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/sandeepraulo/Downloads/HiApp-master/hiapp/platforms/ios/cordova/node_modules/q/q.js:816:13)
    at /Users/sandeepraulo/Downloads/HiApp-master/hiapp/platforms/ios/cordova/node_modules/q/q.js:570:49
(node:1193) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1193) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BelinChung** [comment]
Please make sure `icon-small@2x.png` in this path `www/static/icons/ios/icon-small@2x.png`
